#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  cd "$shome"

  mkdir -p "$shome/vendor"
  rm -rf "$shome/vendor/dd-agent"
  git clone -b 5.8.4 git@github.com:DataDog/dd-agent "$shome/vendor/dd-agent"
  cd "$shome/vendor/dd-agent"

  block compile bundler
  block compile virtualenv27
  source vendor/virtualenv/bin/activate

  "$shome/script/update"
}

bootstrap
