#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  if [[ ! -x "$(type -P agent.py)" ]]; then
    return 1
  fi

  if [[ ! -x "$(type -P ddagent.py)" ]]; then
    return 1
  fi

  if [[ ! -x "$(type -P dogstatsd.py)" ]]; then
    return 1
  fi

  return 0
}

source sub "$BASH_SOURCE" "$@"
