#!/usr/bin/env bash

function bootstrap {
  local shome="$(cd -P -- "$(dirname -- "$BASH_SOURCE")/.." && pwd -P)"
  source "$shome/script/profile"

  ln -nfs ../vendor/dd-agent/agent.py "$shome/bin/"
  ln -nfs ../vendor/dd-agent/ddagent.py "$shome/bin/"
  ln -nfs ../vendor/dd-agent/dogstatsd.py "$shome/bin/"
}

bootstrap
